### ISSUE TITLE
Build not working on Windows 8.1 x64

### ISSUE THREAD

**Issue by jonas-koeritz** [steffengy/node-raw-socket#5]
When trying to build this module on my machine three errors stop it from working.

```
..\src\raw.cc(603): error C3861: "bzero": Bezeichner wurde nicht gefunden. [C:\...\raw-socket2\build\raw.vcxproj]
..\src\raw.cc(607): error C3861: "inet_pton": Bezeichner wurde nicht gefunden. [C:\...\raw-socket2\build\raw.vcxproj]
..\src\raw.cc(614): error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)' : Konvertierung von Argument 4 von 'int *' in 'const char *' nicht möglich [C:\...\raw-socket2\build\raw.vcxproj]
```
